"""quiz subsystem: quizzes, quiz_questions, quiz_answers

Revision ID: 3523b983b688
Revises: c4e584f84120
Create Date: 2026-09-08 23:14:19.564175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3523b983b688'
down_revision: Union[str, Sequence[str], None] = 'c4e584f84120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=60), nullable=True),
    sa.Column('unit', sa.String(length=200), nullable=True),
    sa.Column('concept', sa.String(length=200), nullable=True),
    sa.Column('reveal_feedback', sa.Boolean(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quizzes_group_name'), ['group_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_quizzes_level_id'), ['level_id'], unique=False)

    op.create_table('quiz_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('qtype', sa.String(length=20), nullable=False),
    sa.Column('competency', sa.String(length=30), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('stimulus', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('indicators', sa.JSON(), nullable=True),
    sa.Column('penalties', sa.JSON(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('auto_scored', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_questions_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.Column('auto_score', sa.Float(), nullable=True),
    sa.Column('manual_score', sa.Float(), nullable=True),
    sa.Column('teacher_confirmed', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['quiz_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'student_id', name='uq_quiz_answer')
    )
    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_answers_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_answers_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_answers_student_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_answers_question_id'))

    op.drop_table('quiz_answers')
    with op.batch_alter_table('quiz_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_questions_quiz_id'))

    op.drop_table('quiz_questions')
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quizzes_level_id'))
        batch_op.drop_index(batch_op.f('ix_quizzes_group_name'))

    op.drop_table('quizzes')
    # ### end Alembic commands ###
