"""classroom sessions: quiz_sessions, session_students

Revision ID: b951428a7459
Revises: 3523b983b688
Create Date: 2026-09-09 08:48:19.574114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b951428a7459'
down_revision: Union[str, Sequence[str], None] = '3523b983b688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_sessions_group_name'), ['group_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_sessions_quiz_id'), ['quiz_id'], unique=False)

    op.create_table('session_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=False),
    sa.Column('device_token', sa.String(length=64), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['quiz_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'student_id', name='uq_session_student')
    )
    with op.batch_alter_table('session_students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_students_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_students_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_students_student_id'))
        batch_op.drop_index(batch_op.f('ix_session_students_session_id'))

    op.drop_table('session_students')
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_sessions_quiz_id'))
        batch_op.drop_index(batch_op.f('ix_quiz_sessions_group_name'))

    op.drop_table('quiz_sessions')
    # ### end Alembic commands ###
