"""initial philotech schema

Revision ID: c4e584f84120
Revises: 
Create Date: 2026-09-08 21:14:59.336363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4e584f84120'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('essay_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('methodology_type', sa.Enum('تحليل نص', 'قولة', 'سؤال إشكالي', 'مهارة جزئية', name='methodology_type_enum', native_enum=False), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('essay_exercises', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_essay_exercises_level_id'), ['level_id'], unique=False)

    op.create_table('evaluation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('event_type', sa.Enum('تقويم تشخيصي', 'تمرين', 'فرض', name='event_type_enum', native_enum=False), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluation_events_level_id'), ['level_id'], unique=False)

    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_modules_level_id'), ['level_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=60), nullable=True),
    sa.Column('massar_code', sa.String(length=40), nullable=True),
    sa.Column('login_code', sa.String(length=40), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_code'),
    sa.UniqueConstraint('massar_code')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_group_name'), ['group_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_level_id'), ['level_id'], unique=False)

    op.create_table('class_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=60), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('skills_summary', sa.JSON(), nullable=True),
    sa.Column('weakest_skill', sa.String(length=60), nullable=True),
    sa.Column('ai_intervention_plan', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['evaluation_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_reports_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_reports_group_name'), ['group_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_reports_level_id'), ['level_id'], unique=False)

    op.create_table('concepts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concepts_module_id'), ['module_id'], unique=False)

    op.create_table('student_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('skill_profile', sa.JSON(), nullable=True),
    sa.Column('ai_intervention_plan', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['evaluation_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_reports_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_reports_student_id'), ['student_id'], unique=False)

    op.create_table('axes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('axes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_axes_concept_id'), ['concept_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_axes_module_id'), ['module_id'], unique=False)

    op.create_table('philosophical_texts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('axis_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('source', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('text_type', sa.Enum('أساسي', 'محاور', 'داعم', name='text_type_enum', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['axis_id'], ['axes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('philosophical_texts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_philosophical_texts_axis_id'), ['axis_id'], unique=False)

    op.create_table('analysis_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('target_skill', sa.Enum('إشكال', 'مفاهيم', 'أطروحة', 'بنية حجاجية', 'استنتاج', name='target_skill_enum', native_enum=False), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['philosophical_texts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_questions_text_id'), ['text_id'], unique=False)

    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('essay_id', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('skill_deficits', sa.JSON(), nullable=True),
    sa.Column('teacher_confirmed', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('NOT (question_id IS NOT NULL AND essay_id IS NOT NULL)', name='ck_submission_single_target'),
    sa.ForeignKeyConstraint(['essay_id'], ['essay_exercises.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['evaluation_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['analysis_questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'student_id', 'question_id', 'essay_id', name='uq_submission_scope')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_submissions_essay_id'), ['essay_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_submissions_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_submissions_student_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_question_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_event_id'))
        batch_op.drop_index(batch_op.f('ix_submissions_essay_id'))

    op.drop_table('submissions')
    with op.batch_alter_table('analysis_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_questions_text_id'))

    op.drop_table('analysis_questions')
    with op.batch_alter_table('philosophical_texts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_philosophical_texts_axis_id'))

    op.drop_table('philosophical_texts')
    with op.batch_alter_table('axes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_axes_module_id'))
        batch_op.drop_index(batch_op.f('ix_axes_concept_id'))

    op.drop_table('axes')
    with op.batch_alter_table('student_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_reports_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_reports_event_id'))

    op.drop_table('student_reports')
    with op.batch_alter_table('concepts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concepts_module_id'))

    op.drop_table('concepts')
    with op.batch_alter_table('class_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_reports_level_id'))
        batch_op.drop_index(batch_op.f('ix_class_reports_group_name'))
        batch_op.drop_index(batch_op.f('ix_class_reports_event_id'))

    op.drop_table('class_reports')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_level_id'))
        batch_op.drop_index(batch_op.f('ix_students_group_name'))

    op.drop_table('students')
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modules_level_id'))

    op.drop_table('modules')
    with op.batch_alter_table('evaluation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluation_events_level_id'))

    op.drop_table('evaluation_events')
    with op.batch_alter_table('essay_exercises', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_essay_exercises_level_id'))

    op.drop_table('essay_exercises')
    op.drop_table('levels')
    # ### end Alembic commands ###
